### ISSUE TITLE
Create 10X branch

### ISSUE THREAD

**Issue by athompson-git** [cms-mual/MuAlPhysicsValidation#7]
I'd like to have a 10X branch of Physics Validation so that we can make changes relevant for 10X CMSSW code, e.g.

MuAlRefit/CRAB_MC_Zmumu_ideal/refit_ideal_MuAl_cfg.py

needs to have it's extended geometry config updated.

**Comment by demarley** [comment]
Done.

https://github.com/cms-mual/MuAlPhysicsValidation/tree/CMSSW_10_0_X
